name: storeapp
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'




dependencies:
  flutter:
    sdk: flutter

  # Utility packages
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  #Icons

  iconsax:   ^0.0.8
  cupertino_icons: ^1.0.2
  # state Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # product Specific
  readmore: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  async: ^2.11.0
  characters: ^1.3.0
  clock: ^1.1.1
  collection: ^1.18.0
  http_parser: ^4.0.2
  material_color_utilities: ^0.11.1
  meta: ^1.15.0
  path: ^1.9.0
  string_scanner: ^1.2.0
  firebase_core: ^3.8.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  boolean_selector: ^2.1.1
  leak_tracker: ^10.0.5
  leak_tracker_flutter_testing: ^3.0.5
  lints: ^3.0.0
  matcher: ^0.12.16+1
  stack_trace: ^1.11.1
  test_api: ^0.7.2
  vm_service: ^14.2.5




  flutter_lints: ^3.0.1




flutter:

  uses-material-design: true

  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/reviews/
    - assets/images/products/
    - assets/images/on_boarding_images/
    - assets/images/content/
    - assets/images/banners/
    - assets/icons/brands/
    - assets/icons/categories/
    - assets/icons/payment_methods/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-light.ttf
          weight: 300
        - asset:   assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800